- name: Install Markdown TOC Generator
  run: npm install -g markdown-toc@^1.5
on:
  push:
    branches:
      - '*'
      
jobs:
  generate_toc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install Markdown TOC Generator
        run: npm install -g markdown-toc@^1.5
        
      - name: Generate Table of Contents
        run: markdown-toc -i README.md
